name: Miniworlds
version: 1.0.0
main: com.minerforstone.miniworlds.Miniworlds
description: A tiny civilization game in Minecraft!
author: MinerForStone
api-version: '1.20'

commands:
  craft:
    description: "Opens the crafting grid"
  minihelp:
    description: "Displays Miniworlds commands"
  teams:
    description: "Opens the team selection menu"
  shop:
    description: "Opens the shop"